# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-19 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20191121_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='kind',
            field=models.CharField(max_length=8, verbose_name=b'\xe6\xad\x8c\xe6\x9b\xb2\xe5\x88\x86\xe7\xb1\xbb'),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_dir',
            field=models.CharField(max_length=128, verbose_name=b'\xe6\xad\x8c\xe6\x9b\xb2\xe8\xb7\xaf\xe5\xbe\x84'),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_name',
            field=models.CharField(max_length=64, verbose_name=b'\xe6\xad\x8c\xe5\x90\x8d'),
        ),
        migrations.AlterField(
            model_name='music',
            name='singer',
            field=models.CharField(max_length=24, verbose_name=b'\xe6\xad\x8c\xe6\x89\x8b'),
        ),
    ]
