# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-19 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0004_discuss_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discuss',
            name='created_time',
            field=models.DateTimeField(auto_now=True, verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='discuss',
            name='message',
            field=models.TextField(verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe5\x86\x85\xe5\xae\xb9'),
        ),
        migrations.AlterField(
            model_name='discuss',
            name='parent_id',
            field=models.IntegerField(default=0, verbose_name=b'\xe7\x88\xb6\xe8\xaf\x84\xe8\xae\xbaID'),
        ),
    ]
